global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'test_dev_was'
    ec2_sd_configs:
      - region: 'us-west-2'
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_eks_cluster_name]
        regex: 'test_dev_was'
        action: keep

sns_configs:


